KhalimulinDD: Testing methods
eugene-okulik/KhalimulinDD pull request #18
Opened 2024-09-11 20:07 UTC by KhalimulinDD

2024-09-12 09:15 UTC, eugene-okulik requested changes
В плане задания - всё хорошо.  
В плане питона - не очень. Нужно избавиться от повторений. Например, функция create_object_2() ничем не отличается от функции create_object_1()

2024-09-12 09:15 UTC, eugene-okulik commented on homework/dmitriy_khalimulin/Lesson_18_API/task_1.py
> +clear_object_3(update_object_3(create_object_3()))
Это чота жостко выглядит ))))

2024-09-12 09:15 UTC, eugene-okulik commented on homework/dmitriy_khalimulin/Lesson_18_API/task_1.py
> +    print(delete_response.json())
Вместо трех одинаковых методов, мог быть один, который принимает id того, что нужно удалить.

2024-09-12 09:15 UTC, eugene-okulik commented on homework/dmitriy_khalimulin/Lesson_18_API/task_1.py
> +clear_object_3(update_object_3(create_object_3()))
Всегда есть стремление оформить всё одной строкой, но не всегда это имеет смысл. Здесь было бы лучше
```python
obj_id = create_object_3()
update_object_3(obj_id)
clear_object_3(obj_id)
```

2024-09-12 10:10 UTC, KhalimulinDD commented
Возможно стоит сделать вот так, но соответственно в будущем это надо отдельно каждые кейсы описывать)

2024-09-12 14:28 UTC, KhalimulinDD commented
Сделал улучшенное обновление, думаю что так будет намного лучше

2024-09-13 12:52 UTC, eugene-okulik approved these changes
Вот теперь идеально, да.

2024-09-13 12:52 UTC, merged