KhalimulinDD: New file API with decorator and change folders
eugene-okulik/KhalimulinDD pull request #19
Opened 2024-09-13 21:38 UTC by KhalimulinDD

2024-09-13 21:42 UTC, KhalimulinDD commented
Изменил еще в добавок название папок, добавил слеш, почему изменили файлы в Lesson_3 не совсем понял, я их не менял

2024-09-14 09:48 UTC, eugene-okulik approved these changes
Круто, что ты умеешь пользоваться непрямой параметризацией. Но она не зря сделана так костыльно и никто не собирается это менять - она не очень часто действительно нужна.  
Непрямые параметризации можешь здесь оставить, если лень переделывать. Но первый тест нужно переделать.

2024-09-14 09:48 UTC, eugene-okulik commented on homework/dmitriy_khalimulin/Lesson_19_API/test_task_1.py
> +    assert create_deleted is not None, "Объект не был создан"
Здесь, конечно, могло бы проканать, но только в этом задании, так как мы пока что просто учимся делать структуру. Но в реальной жизни тест на создание объекта не будет пользоваться фикстурой, т.к. для тестирования создания объекта тебе нужно управлять тем, с какими данными создается объект. А в конце теста проверять, что объект создался именно с теми данными, с которыми создавался.  
Поэтому праильнее здесь будет сформировать запрос, отправить его и проверить результат.

2024-09-14 09:48 UTC, eugene-okulik commented on homework/dmitriy_khalimulin/Lesson_19_API/test_task_1.py
> +@pytest.mark.parametrize('create_deleted', ['Iphone'], indirect=True)
Здесь в непрямой параметризации нет смысла. Здесь есть больше смысла в прямой параметризации, когда мы в качестве, например name передаем разные значения, проверяя, что все они нормально перевариваются апишкой
```python
@pytest.mark.parametrize('name', ['Iphone', '     ', '&*^%^%$%$'])
```

2024-09-14 09:48 UTC, eugene-okulik commented on homework/dmitriy_khalimulin/Lesson_19_API/test_task_1.py
> +@pytest.mark.parametrize('create_deleted', ['Samsung'], indirect=True)
Ну и здесь непрямая параметризация ничего не дает. Нам здесь вполне достаточно какого-то чуть ли не захардкоженного (или взятого из файла с тестовыми данными) объекта. Ведь здесь мы проверяем не создание объекта с разными названиями, мы в этом тесте проверяем изменение существующего объекта. Непрямая параметризация нужна была бы если бы в зависимости от того, с каким параметром запускается фикстура, создавались бы абсолютно разные типы объектов. Но это тогда был не тест изменения объекта. А было бы несколько тестов: один на изменение объектов такого типа, другой на изменение объектов другого типа.

2024-09-14 09:48 UTC, eugene-okulik requested changes
Случайно выбрал "Approve" вместо "Request Changes", исправляюсь ))

2024-09-16 09:03 UTC, KhalimulinDD commented
Есть конечно сомнения по созданной фикстуре на создание в конце, возможно стоило сделать как то по другому, пока не додумал как)
А еще почему то не могу писать описание коммитов на латинице с заглавной буквы, на кириллице все нормально, раньше все было хорошо, странно

2024-09-16 09:24 UTC, eugene-okulik commented
> Есть конечно сомнения по созданной фикстуре на создание в конце, возможно стоило сделать как то по другому, пока не додумал как) А еще почему то не могу писать описание коммитов на латинице с заглавной буквы, на кириллице все нормально, раньше все было хорошо, странно

В фикстуре всё правильно  
Странно, что гит не дает писать комменты с заглавной буквы.

2024-09-16 09:25 UTC, eugene-okulik approved these changes

2024-09-16 09:25 UTC, merged