KhalimulinDD: Ready-made project for API automation"
eugene-okulik/KhalimulinDD pull request #21
Opened 2024-09-19 16:28 UTC by KhalimulinDD

2024-09-20 07:52 UTC, eugene-okulik requested changes

2024-09-20 07:52 UTC, eugene-okulik commented on test_api_khalimulindd/tests/test_api_project.py
> +    create_post_endpoint.create_new_post()
Это не является шагом теста. Это является предусловием этого теста, а предусловия оформляются в фикстурах.

2024-09-20 07:52 UTC, eugene-okulik commented on test_api_khalimulindd/tests/test_api_project.py
> +    delete_post_endpoint.delete_post(created_post_id)
И это не является шагом этого теста. Это является постусловием. Они тоже делаются в фикстурах. Так же, как делали в задании 18.

2024-09-20 17:04 UTC, KhalimulinDD commented
Женя нужен твой совет, по поводу теста на удаление, я всю голову сломал как сделать элементарную проверку что в ответе на удаление 200 и в message присутствует айдишник, вроде осталось так элементарно, но уже закипел)
Там еще создал метод check_post_deleted в классе и обращался к нему, но все равно не получается, нужна помощь)

2024-09-20 19:42 UTC, KhalimulinDD commented
Вот я еще подумал и сделал так)
Подскажи пожалуйста правильно ли, если даже правильно то подскажи как можно еще оптимизировать если возможно

2024-09-20 20:42 UTC, KhalimulinDD commented
Вот как сдал работу, подумал что возможно стоит убрать метод в котором происходит создание и удаление одновременно, и оставить только их по отдельности, но вот что можно придумать с переменными сверху в тестах, возможно их можно куда нибудь убрать ?

2024-09-21 07:56 UTC, eugene-okulik requested changes
В целом, уже получше, но запутался в фикстурах.  
И еще, ты во всех тестах работаешь с какими-то постами. Я понимаю, что это ты из-за того, что я в занятии показывал раоту с постами. Но если убрать контекст занятия и посмотреть на твои тесты в отрыве от этого - о каких постах речь? В апишке создаются объекты (они там так и называются), можно еще называть это айтемы, продукты. Но это точно не посты. Это на занятии я показывал все на примере апишки соцсети, а там посты (публикации).  
В автоматизации тестировании очень важно, чтобы названия точно отражали то, что под ними скрывается.

2024-09-21 07:56 UTC, eugene-okulik commented on test_api_khalimulindd/endpoints/delete_post.py
> +        assert message == expected_message, f"Expected message '{expected_message}', but got '{message}'"
Эту штуку можно было сделать без хардкода текста сообщения
```python
assert created_post_id in message
```

2024-09-21 07:56 UTC, eugene-okulik commented on test_api_khalimulindd/tests/test_api_project.py
> +    delete_post_endpoint.check_that_post_id_in_massage(created_new_post_id)
Здесь вижу лишнюю фикстуру. Обычно делается так
```python
delete_post_endpoint.delete_post(created_new_post_id)
delete_post_endpoint.check_that_status_is_200()
delete_post_endpoint.check_that_post_id_in_massage(created_new_post_id)
```

2024-09-21 07:56 UTC, eugene-okulik commented on test_api_khalimulindd/tests/test_api_project.py
> +    create_and_cleanup_post.check_response_name_is_correct(name)
Здесь ты работаешь не с той фикстурой. Эта фикстура сама создает и удаляет объект. Кстати, в этой апи ты работаешь не с постами, а с объектами (это в видео я работал с постами - там была апишка для управления постами в соцсети). 
А здесь тебе нужно работать с ендпоинтом, который умеет создавать и удалять объекты - `create_post_endpoint`. Точно так же , как у тебя сделано в следующем тесте.

2024-09-21 07:56 UTC, eugene-okulik commented on test_api_khalimulindd/tests/test_api_project.py
> +    created_new_post_id = create_and_cleanup_post.post_id
Чтобы в каждом тесте не делать такое, фикстура может сразу возвращать айди, ведь кроме айди тебе из этой фикстуры ничего не надо.

2024-09-23 13:13 UTC, KhalimulinDD commented
Апишка очень не стабильная, то работает то нет, вот уже 2 дня не работает, вроде все так сделал, если есть малейшие не дочеты или можно еще как то оптимизировать этот проект то скажи обязательно

2024-09-23 15:29 UTC, eugene-okulik commented
> Апишка очень не стабильная, то работает то нет, вот уже 2 дня не работает, вроде все так сделал, если есть малейшие не дочеты или можно еще как то оптимизировать этот проект то скажи обязательно

Да, в последние несколько дней она что-то начала сбоить. Раньше работала как часы.

2024-09-23 15:58 UTC, eugene-okulik requested changes

2024-09-23 15:58 UTC, eugene-okulik commented on test_api_khalimulindd/conftest.py
> +    return _create_object
Сейчас ты сделал фикстуру, которая ничего не делает и возвращает функцию. Но эта фикстура должна создавать сама объект. Вот как она должна выглядеть:  
```python
def create_object_fixture(create_object_endpoint):
    """Фикстура для создания обьекта"""
    create_object_endpoint.create_new_object(payload=default_payload)  # здесь тебе обычно не важно с какими именно данными создастся объект - это могут быть всегда одни и те же данные.
    created_object_id = create_object_endpoint.object_id
    created_name = create_object_endpoint.object_name
    return created_object_id
```

2024-09-23 15:58 UTC, eugene-okulik commented on test_api_khalimulindd/tests/test_api_project.py
> +    cleanup_object_fixture(object_id=created_object_id)
В этих двух тестах не нужно использовать фикстуру создания объекта. Так как создание объекта в этих тестах является не предусловием этих тестов, а шагами этих тестов.

2024-09-23 15:58 UTC, eugene-okulik commented on test_api_khalimulindd/tests/test_api_project.py
> +    create_object_endpoint, created_object_id = create_object_fixture(payload=None)
Здесь непонятно зачем ты переназначаешь переменную  create_object_endpoint, ведь в этой переменной хранится объект ендпоинта из фикстуры  create_object_endpoint.  
Если сделать фикстуру create_object_fixture такой как я написал, то эта строка вообще не нужна, тест был бы такой
```python
def test_create_single_object(create_object_fixture, cleanup_object_fixture, create_object_endpoint):
    update_object_put_endpoint.update_object_put(create_object_fixture, payload=None)

    # Проверка ответа после обновления
    update_object_put_endpoint.check_that_status_is_200()
    update_object_put_endpoint.check_response_name_is_correct(update_object_name)  # Здесь ты не можешь нормально оформить проверку, так как ты при запуске апдейта не задал на что нужно проапдейтить, поэтому тест не знает с какими данными он работает. Но как раз тест и должен знать с какими тестовыми данными он работает.
```

2024-09-23 15:58 UTC, eugene-okulik commented on test_api_khalimulindd/tests/test_api_project.py
> +    cleanup_object_fixture(object_id=update_object_id)
Это не является шагом теста. Это должно быть оформлено как постусловие фикстуры create_object_fixture (должно находиться после yield). Так же как в задании 19 ты делал в фикстуре `create_deleted`

2024-09-23 15:58 UTC, eugene-okulik commented on test_api_khalimulindd/tests/test_api_project.py
> +    create_object_endpoint, created_object_id = create_object_fixture(payload=None)
Чтобы тест понимал с какими данными он работает, при апдейте ты должен указать данные, которые будут использованы при апдейте. Было бы как-то так
```python
update_data = {
            "data": {
                "year": 2000,
                "price": 29292,
                "CPU model": "Intel -Updated",
                "Hard disk size": "2 TB - Updated"
            }
        }
update_object_put_endpoint.update_object_put(create_object_fixture, payload=update_data)

update_object_put_endpoint.check_that_status_is_200()
update_object_put_endpoint.check_response_name_is_correct(update_data['name']) # только вот в данных нет поля name - не понятно, что проверяется
```

2024-09-23 15:58 UTC, eugene-okulik commented on test_api_khalimulindd/tests/test_api_project.py
> +    cleanup_object_fixture(object_id=created_object_id)
Это является шагом теста, не пред или постусловием. Через фикстуры мы реализуем только пред и постусловия.  
Здесь нужно пользоваться объектом delete_object_endpoint и вызывать у него метод удаления объекта.

2024-09-25 03:47 UTC, KhalimulinDD commented
Переделал на другую апишку, с прошлой апишкой все плохо, уже несколько дней так и не работает

2024-09-25 11:43 UTC, eugene-okulik requested changes
Осталось чуть-чуть )))

2024-09-25 11:43 UTC, eugene-okulik commented on test_api_khalimulindd/tests/test_api_project.py
> +    request.function.product_id = product_id
А тебе здесь product_id не нужен. Можно не плодить лишние переменные. просто сразу сделать
```python
request.function.product_id = create_product_endpoint.create_new_product()
```

2024-09-25 11:43 UTC, eugene-okulik commented on test_api_khalimulindd/tests/test_api_project.py
> +    body["name"] = name
Ты сформировал боди, но не воспользовался им при создании продукта. А метод `create_new_product()` и не имеет возможности принять боди из теста, а должен. Т.е. сейчас ты из теста не можешь управлять тем, с какими данными создастся продукт. А именно из теста ты и должен этим управлять.

2024-09-25 11:43 UTC, eugene-okulik commented on test_api_khalimulindd/tests/test_api_project.py
> +    create_product_endpoint.check_that_status_is_200()
Этот тест такой же как предыдущий, но без параметров. Ничего нового он не проверяет.

2024-09-25 11:48 UTC, KhalimulinDD commented on test_api_khalimulindd/tests/test_api_project.py
> +    create_product_endpoint.check_that_status_is_200()
То есть этот тест впринципе не нужен и его можно удалить?

2024-09-26 08:37 UTC, eugene-okulik commented on test_api_khalimulindd/tests/test_api_project.py
> +    create_product_endpoint.check_that_status_is_200()
угу

2024-09-26 08:38 UTC, eugene-okulik approved these changes

2024-09-26 08:39 UTC, merged